# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MCMC <- function(EC_numeric_multi_map, Y_unique, N_peptides_per_protein, delta_prior, PSM_multi_map, N, M, K, burn_in, thin, trace) {
    .Call(`_IsoBayes_MCMC`, EC_numeric_multi_map, Y_unique, N_peptides_per_protein, delta_prior, PSM_multi_map, N, M, K, burn_in, thin, trace)
}

MCMC_PEP <- function(EC_numeric_multi_map, PSM_multi_map, PEP, M, EC_numeric_unique, PSM_unique, PEP_unique, M_unique, N_peptides_per_protein, delta_prior, N, K, burn_in, thin, trace) {
    .Call(`_IsoBayes_MCMC_PEP`, EC_numeric_multi_map, PSM_multi_map, PEP, M, EC_numeric_unique, PSM_unique, PEP_unique, M_unique, N_peptides_per_protein, delta_prior, N, K, burn_in, thin, trace)
}

MCMC_Unique <- function(Y_unique, delta_prior, N, K, burn_in, thin, trace) {
    .Call(`_IsoBayes_MCMC_Unique`, Y_unique, delta_prior, N, K, burn_in, thin, trace)
}

