#' @useDynLib IsoBayes, .registration = TRUE
#' @importFrom methods formalArgs
#' @importFrom stats aggregate.data.frame
#' @importFrom data.table fread
#' @importFrom data.table setnames
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 geom_bar
#' @importFrom ggplot2 theme_bw
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 position_dodge
#' @importFrom ggplot2 aes_string
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 ggtitle
#' @importFrom ggplot2 xlab
#' @importFrom ggplot2 ylab
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 scale_color_manual
#' @importFrom ggplot2 geom_errorbar
#' @importFrom glue glue
#' @importFrom Rcpp sourceCpp
#' @importFrom doParallel registerDoParallel
#' @importFrom doRNG '%dorng%'
#' @importFrom parallel makeCluster
#' @importFrom parallel stopCluster
#' @importFrom foreach foreach
#' @importFrom iterators iter
#' @importFrom stats median
#' @importFrom stats na.omit
#' @importFrom HDInterval hdi
#' @importFrom SummarizedExperiment SummarizedExperiment
#' @importFrom SummarizedExperiment colData
#' @importFrom SummarizedExperiment assay
#' @importFrom methods is
#' @importFrom S4Vectors DataFrame
#' @importFrom S4Vectors metadata
NULL